name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  Mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mirror
        run: |
          git remote add push https://$CODEBERG_USENAME:$CODEBERG_TOKEN@codeberg.org/Neptunium93/.profile.git
          git fetch push
          git push -u push master
        env:
          CODEBERG_USENAME: ${{ secrets.CODEBERG_USENAME }}
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
